"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { clearAllData, getProfile, saveProfile, trackEvent } from "@/lib/experience/storage";
import type { ChildProfile, FamilyProfile, ShoppingConcern } from "@/lib/experience/types";
import { clearCloudData, cloudEnabled, loadCloudProfile, saveCloudProfile } from "@/lib/experience/cloud";
import { createAuthBrowserClient } from "@/lib/supabase/browser";

export function FamilyEditor() {
  const router = useRouter();
  const [profile, setProfile] = useState<FamilyProfile | null>(null);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { if (cloudEnabled) void loadCloudProfile().then(setProfile).catch(() => setError("Không thể tải hồ sơ.")); else setProfile(getProfile()); }, []);
  if (!profile) return <div className="container account-page"><h1>Chưa có hồ sơ gia đình</h1><Link href="/">Bắt đầu trò chuyện với Family AI →</Link></div>;
  function updateChild(index: number, patch: Partial<ChildProfile>) { setProfile((current) => current ? { ...current, children: current.children.map((child, at) => at === index ? { ...child, ...patch } : child) } : current); setSaved(false); }
  function addChild() { setProfile((current) => current && current.children.length < 5 ? { ...current, children: [...current.children, { id: crypto.randomUUID() }] } : current); setSaved(false); }
  function removeChild(index: number) { setProfile((current) => current ? { ...current, children: current.children.filter((_, at) => at !== index) } : current); setSaved(false); }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!profile) return; const updated = { ...profile, updatedAt: new Date().toISOString() }; setError(""); try { if (cloudEnabled) await saveCloudProfile(updated); saveProfile(updated); setProfile(updated); setSaved(true); trackEvent("family_profile_updated"); } catch { setError("Chưa lưu được hồ sơ. Vui lòng thử lại."); } }
  async function erase() { if (!window.confirm("Xóa hồ sơ, lịch sử trò chuyện và sản phẩm đã lưu?")) return; setError(""); try { if (cloudEnabled) await clearCloudData(); clearAllData(); router.push("/"); } catch { setError("Chưa xóa được toàn bộ dữ liệu. Vui lòng thử lại."); } }
  async function signOut() { const client = createAuthBrowserClient(); if (!client) return; const { error: authError } = await client.auth.signOut(); if (authError) { setError("Chưa đăng xuất được. Vui lòng thử lại."); return; } clearAllData(); router.push("/sign-in"); }
  return <div className="container account-page"><div className="breadcrumb"><Link href="/shop">Tư vấn</Link><span>/</span>Gia đình</div><div className="account-heading"><p className="eyebrow accent">BỐI CẢNH GIA ĐÌNH</p><h1>Family AI hiểu gia đình bạn hơn</h1><p>Chỉ giữ thông tin cần để chọn sản phẩm. Bạn có thể chỉnh sửa bất cứ lúc nào.</p></div>
    <form className="family-form" onSubmit={submit}><section className="form-card"><div><span className="section-number">01</span><h2>Thông tin của bé</h2><p>Cân nặng và size giúp loại bỉm không phù hợp. Có thể lưu tối đa 5 bé.</p></div><div className="children-editor">{profile.children.map((child, index) => <div className="child-editor" key={child.id}><div className="child-editor-heading"><strong>Bé {index + 1}</strong><button type="button" onClick={() => removeChild(index)}>Xóa bé này</button></div><div className="form-grid"><label>Tên gọi của bé<input value={child.name ?? ""} onChange={(event) => updateChild(index, { name: event.target.value })} placeholder="Ví dụ: Gold" /></label><label>Cân nặng hiện tại (kg)<input type="number" min="2" max="30" step="0.1" value={child.weightKg ?? ""} onChange={(event) => updateChild(index, { weightKg: event.target.value ? Number(event.target.value) : undefined })} /></label><label>Tuổi (tháng)<input type="number" min="0" max="48" value={child.ageMonths ?? ""} onChange={(event) => updateChild(index, { ageMonths: event.target.value ? Number(event.target.value) : undefined })} /></label><label>Size bỉm hiện tại<select value={child.diaperSize ?? ""} onChange={(event) => updateChild(index, { diaperSize: event.target.value || undefined })}><option value="">Chưa rõ</option>{["NB", "S", "M", "L", "XL", "XXL"].map((size) => <option key={size}>{size}</option>)}</select></label></div></div>)}{profile.children.length < 5 && <button className="add-child" type="button" onClick={addChild}>＋ Thêm bé</button>}</div></section>
      <section className="form-card"><div><span className="section-number">02</span><h2>Ưu tiên mua sắm</h2><p>Giúp Family AI sắp xếp các lựa chọn theo nhu cầu của bạn.</p></div><div className="form-grid"><label>Ưu tiên giá<select value={profile.pricePreference} onChange={(event) => { setProfile({ ...profile, pricePreference: event.target.value as FamilyProfile["pricePreference"] }); setSaved(false); }}><option value="budget">Giá tốt</option><option value="balanced">Cân bằng</option><option value="premium">Cao cấp</option></select></label><label>Điều quan trọng nhất<select value={profile.mainConcern ?? ""} onChange={(event) => { setProfile({ ...profile, mainConcern: event.target.value as ShoppingConcern || undefined }); setSaved(false); }}><option value="">Chưa chọn</option><option value="night">Dùng ban đêm</option><option value="leak">Hạn chế tràn</option><option value="soft">Mỏng nhẹ</option><option value="sensitive">Da nhạy cảm</option><option value="value">Giá trị theo đơn vị</option></select></label><label>Ngân sách tối đa thường dùng (đ)<input type="number" min="50000" step="1000" value={profile.maxBudget ?? ""} onChange={(event) => { setProfile({ ...profile, maxBudget: event.target.value ? Number(event.target.value) : undefined }); setSaved(false); }} /></label></div></section>
      <section className="form-card"><div><span className="section-number">03</span><h2>Quyền riêng tư</h2><p>{cloudEnabled ? "Thông tin được lưu trong tài khoản của bạn." : "Thông tin được lưu trên trình duyệt này trong bản trải nghiệm."}</p></div><label className="consent-line"><input type="checkbox" checked={profile.aiConsent} onChange={(event) => { setProfile({ ...profile, aiConsent: event.target.checked }); setSaved(false); }} /> Cho phép gửi nội dung tôi nhập tới nhà cung cấp AI khi hệ thống được cấu hình.</label></section>
      <div className="form-actions"><button className="button primary" type="submit">Lưu hồ sơ</button>{saved && <span>Đã lưu thay đổi.</span>}{error && <span className="form-error">{error}</span>}<Link href="/shop">Quay lại tư vấn →</Link></div></form><button className="danger-link" onClick={() => void erase()}>Xóa hồ sơ và dữ liệu mua sắm</button>{cloudEnabled && <button className="danger-link" onClick={() => void signOut()}>Đăng xuất</button>}</div>;
}
